name: Build, Publish and Update GitOps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Set image tag
        id: meta
        run: |
          # použijeme skrátený SHA ako tag
          TAG=${GITHUB_SHA::8}
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest

  update-gitops:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: johno221/web-page-gitops
          token: ${{ secrets.GITOPS_PAT }}
          path: web-page-gitops

      - name: Update image tag in values.yaml
        working-directory: web-page-gitops/web-page-chart
        run: |
          NEW_TAG="${{ needs.build-and-push.outputs.image_tag }}"
          echo "Using new tag: ${NEW_TAG}"

          # nahradíme riadok 'tag: "...“' novým tagom
          sed -i "s/^  tag: \".*\"/  tag: \"${NEW_TAG}\"/" values.yaml

          echo "Resulting values.yaml:"
          cat values.yaml

      - name: Commit and push changes
        working-directory: web-page-gitops
        run: |
          git config user.name "web-page-ci"
          git config user.email "ci@users.noreply.github.com"

          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git add web-page-chart/values.yaml
          git commit -m "Update web-page image tag to ${{ needs.build-and-push.outputs.image_tag }}"
          git push
